version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: docs/requirements.txt

# Define branches to build
build:
  max_jobs: 2

versions:
  only:
    - main       # Stable version
    - develop    # Latest version