import sys
import os
import subprocess
import shutil
# Import version directly from _version.py instead of using setuptools_scm
sys.path.insert(0, os.path.abspath(".."))
from vbi._version import __version__

if not shutil.which("pandoc"):
    try:
        import pypandoc
    except ImportError:
        pass
    else:
        os.environ["PATH"] = (
            os.path.dirname(pypandoc.get_pandoc_path())
            + os.pathsep
            + os.environ.get("PATH", "")
        )

needs_sphinx = "0.2"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "numpydoc",
    "sphinx.ext.graphviz",
    "sphinx.ext.viewcode",
    'nbsphinx',
    "sphinx_gallery.gen_gallery",
]

# Execute every script by default; only the ones below are permanently
# excluded, each for a real technical reason (not "not yet migrated" - all
# scripts in this directory are now self-contained, no helpers.py needed):
#   - jax_demo.py: `jax` is an optional vbi extra (pip install vbi[jax]),
#     not in docs/requirements.txt, and it calls sys.exit(1) if missing -
#     which could crash the whole sphinx-gallery build, not just one page.
#   - benchmark_all_backends.py, benchmark_all_models.py,
#     benchmark_cpp_vs_numpy_numba.py, benchmark_numba_vs_numpy.py: need
#     CUDA/JAX/a compiled C++ extension, and bake in wall-clock timings
#     that would be meaningless on shared RTD build hardware. Show a real,
#     pre-rendered plot instead - see reference_images/ and
#     install_reference_images() below.
#   - validate_sweep_backends.py: a pass/fail QA tool, not doc content.
#   - cuda_sweep_demo.py: needs an actual CUDA GPU (RTD has none).
# NOTE: mpr_demo.py and jansen_rit_demo.py import tvb-library, which is NOT
# in docs/requirements.txt - this works for a local build (tvb installed in
# this dev venv) but will break the real RTD build until that's resolved
# (see conversation with user).
_GALLERY_NOT_EXECUTED = (
    "jax_demo", "benchmark_all_backends", "benchmark_all_models",
    "benchmark_cpp_vs_numpy_numba", "benchmark_numba_vs_numpy",
    "validate_sweep_backends", "cuda_sweep_demo",
)
sphinx_gallery_conf = {
    "examples_dirs": ["../examples/simulator_models"],
    "gallery_dirs": ["auto_examples/simulator_models"],
    "filename_pattern": (
        r"^(?!.*(?:" + "|".join(_GALLERY_NOT_EXECUTED) + r")\.py$).*\.py$"
    ),
    "ignore_pattern": r"helpers\.py",
    "plot_gallery": True,
    # Default (True) gives every `# %%` section its own toctree/sidebar
    # entry - with our scripts reusing generic section names (Usage, Setup,
    # Run the demo, Example output) across many pages, the sidebar fills up
    # with ambiguous flat entries. One entry per page is clearer here.
    "nested_sections": False,
    # Hide `# sphinx_gallery_x = y` config-comment lines (e.g. dummy_images)
    # from the rendered page - they're directives for the builder, not
    # content for readers.
    "remove_config_comments": True,
    "download_all_examples": False,
    "first_notebook_cell": (
        "# This notebook is auto-generated from vbi documentation.\n"
        "# Install: pip install vbi\n"
    ),
    "thumbnail_size": (400, 280),
}

# ModelSpec._repr_html_ (see vbi/simulator/spec/model.py) embeds LaTeX
# notes written with single-dollar inline math (e.g. "$\gamma < 0$"), which
# matches Jupyter's default MathJax config but not Sphinx's - Sphinx only
# enables \(...\) for inline math out of the box. Add $...$ so both venues
# render identically.
mathjax3_config = {
    "tex": {"inlineMath": [["\\(", "\\)"], ["$", "$"]]},
}

source_suffix = ".rst"
master_doc = "index"
project = "vbi"
copyright = "2023, Abolfazl Ziaeemehr"
release = version = __version__
nbsphinx_execute = 'never'

default_role = "any"
add_module_names = False
html_theme = "furo"
# Furo defaults to the operating-system preference.  The base template override
# selects light on a visitor's first load while preserving any choice made with
# Furo's theme toggle in localStorage.
templates_path = ["_templates"]
pygments_style = "colorful"
add_function_parentheses = True
html_static_path = ['_static']

# auto_examples/**/*.ipynb are sphinx-gallery-generated by-products; excluding
# them from source discovery stops nbsphinx from also trying to build them
# (it registers .ipynb as a source suffix and would otherwise pick them up
# independently of the .rst page sphinx-gallery already generates for them).
exclude_patterns = [
    "_build",
    "**.ipynb_checkpoints",
    "auto_examples/**/*.ipynb",
]

numpydoc_show_class_members = False
autodoc_member_order = "bysource"
graphviz_output_format = "svg"
toc_object_entries_show_parents = "hide"

# Autodoc configuration for better handling of Numba classes
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Custom autodoc processing for Numba jitclass
def autodoc_skip_member(app, what, name, obj, skip, options):
    """Skip certain members in autodoc to clean up Numba class documentation."""
    # Skip the class_type attribute that Numba adds
    if name == 'class_type':
        return True
    # Skip internal Numba attributes
    if name.startswith('_numba_'):
        return True
    # Skip other unwanted Numba internal attributes
    if name in ['__dict__', '__weakref__', '_type', '_literal_value']:
        return True
    return skip

def process_docstring(app, what, name, obj, options, lines):
    """Process docstrings to clean up Numba class documentation."""
    if what == "class" and hasattr(obj, 'class_type'):
        # This is a Numba jitclass, clean up the docstring
        if lines and 'jitclass' in str(lines[0]):
            # Replace jitclass type info with cleaner description
            lines[0] = "Numba-compiled parameter class for efficient computation."


def on_missing_reference(app, env, node, contnode):
    if node["reftype"] == "any":
        return contnode
    else:
        return None


def sync_examples(app):
    """
    Copy the top-level examples/ tree into docs/examples/ before anything
    else reads the source directory.

    examples/ was moved out of docs/ to the repo root so it's a single
    canonical, non-doc-tooling location. nbsphinx, unlike sphinx-gallery's
    examples_dirs, requires notebooks to physically live inside the Sphinx
    source directory to resolve toctree entries and inline output images.
    A docs/examples symlink pointing outside srcdir was tried first, but
    nbsphinx computes each generated image's path via the notebook's
    *resolved* (symlink-followed) location - since that location is outside
    docs/, the relative path to docs/_build/doctrees/nbsphinx/ came out
    wrong ("../_build/..." resolving to the repo root instead of docs/),
    breaking every notebook's inline output images. A real, gitignored copy
    avoids that entirely.

    Must run before sphinx-gallery's/nbsphinx's own document discovery -
    registered at priority=0, ahead of install_reference_images (priority=1).
    """
    src_dir = os.path.join(app.srcdir, "..", "examples")
    dst_dir = os.path.join(app.srcdir, "examples")
    if not os.path.isdir(src_dir):
        return
    if os.path.islink(dst_dir):
        os.unlink(dst_dir)
    elif os.path.isdir(dst_dir):
        shutil.rmtree(dst_dir)
    shutil.copytree(
        src_dir,
        dst_dir,
        ignore=shutil.ignore_patterns("__pycache__", "outputs", "sbi-logs", "*.pyc"),
    )


def install_reference_images(app):
    """
    Copy pre-rendered reference plots into the exact path sphinx-gallery
    expects for a script's "dummy image" (`# sphinx_gallery_dummy_images = N`),
    so gallery pages for scripts we deliberately don't execute on RTD (CUDA/
    JAX/benchmark demos - see filename_pattern) still show a real plot
    instead of the generic placeholder.

    Must run before sphinx-gallery's own "builder-inited" handler
    (generate_gallery_rst, default priority) - registered at priority=1 to
    guarantee that ordering. Source images live in
    examples/simulator_models/reference_images/ (the one directory
    exempted from the repo's blanket `*.png` gitignore rule); destination is
    the gitignored, regenerated-every-build docs/auto_examples/ tree.
    """
    src_dir = os.path.join(app.srcdir, "..", "examples", "simulator_models", "reference_images")
    dst_dir = os.path.join(app.srcdir, "auto_examples", "simulator_models", "images")
    if not os.path.isdir(src_dir):
        return
    os.makedirs(dst_dir, exist_ok=True)
    for name in os.listdir(src_dir):
        src = os.path.join(src_dir, name)
        dst = os.path.join(dst_dir, f"sphx_glr_{name}")
        if os.path.isfile(src) and not os.path.isfile(dst):
            import shutil
            shutil.copyfile(src, dst)


def setup(app):
    app.connect("missing-reference", on_missing_reference)
    app.connect("autodoc-skip-member", autodoc_skip_member)
    app.connect("autodoc-process-docstring", process_docstring)
    app.connect("builder-inited", sync_examples, priority=0)
    app.connect("builder-inited", install_reference_images, priority=1)

    # sphinx.ext.mathjax only loads its JS on pages with real docutils math
    # nodes (`.. math::`). ModelSpec._repr_html_ embeds LaTeX inside raw HTML
    # (so it also works via Jupyter's rich-display protocol, not just Sphinx),
    # which docutils never sees as "math" - so MathJax would silently not
    # load on those pages without this.
    app.set_html_assets_policy("always")

    # cpp_src = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "vbi", "models", "cpp", "_src"))
    # try:
    #     subprocess.run(["make"], cwd=cpp_src, check=True)
    #     app.info("C++ code compiled successfully.")
    # except subprocess.CalledProcessError as err:
    #     app.warn(f"Failed to compile C++ code in {cpp_src}: {err}")
