import sys
import os
import subprocess
# Import version directly from _version.py instead of using setuptools_scm
sys.path.insert(0, os.path.abspath(".."))
from vbi._version import __version__

needs_sphinx = "0.2"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "numpydoc",
    "sphinx.ext.graphviz",
    "sphinx.ext.viewcode",
    'nbsphinx',
    "sphinx_gallery.gen_gallery",
]

# Scoped to these scripts: they are the only simulator_models scripts
# fixed so far to run without a real __file__ and without a helpers.py
# dependency (see docs/examples/simulator_models helper pattern). Widen
# filename_pattern as more scripts are migrated
# (notes/milestones_documentation.md, Step 4/5).
# NOTE: mpr_demo.py imports tvb-library, which is NOT in docs/requirements.txt -
# this works for a local build (tvb installed in this dev venv) but will break
# the real RTD build until that's resolved (see conversation with user).
sphinx_gallery_conf = {
    "examples_dirs": ["examples/simulator_models"],
    "gallery_dirs": ["auto_examples/simulator_models"],
    "filename_pattern": r"kuramoto_demo\.py|model_equations\.py|mpr_demo\.py|wilson_cowan_demo\.py",
    "ignore_pattern": r"helpers\.py",
    "plot_gallery": True,
    "download_all_examples": False,
    "first_notebook_cell": (
        "# This notebook is auto-generated from vbi documentation.\n"
        "# Install: pip install vbi\n"
    ),
    "thumbnail_size": (400, 280),
}

# ModelSpec._repr_html_ (see vbi/simulator/spec/model.py) embeds LaTeX
# notes written with single-dollar inline math (e.g. "$\gamma < 0$"), which
# matches Jupyter's default MathJax config but not Sphinx's - Sphinx only
# enables \(...\) for inline math out of the box. Add $...$ so both venues
# render identically.
mathjax3_config = {
    "tex": {"inlineMath": [["\\(", "\\)"], ["$", "$"]]},
}

source_suffix = ".rst"
master_doc = "index"
project = "vbi"
copyright = "2023, Abolfazl Ziaeemehr"
release = version = __version__
nbsphinx_execute = 'never'

default_role = "any"
add_module_names = False
html_theme = "furo"
html_theme_options = {
    "default_mode": "light",
}
pygments_style = "colorful"
add_function_parentheses = True
html_static_path = ['_static']

# auto_examples/**/*.ipynb are sphinx-gallery-generated by-products; excluding
# them from source discovery stops nbsphinx from also trying to build them
# (it registers .ipynb as a source suffix and would otherwise pick them up
# independently of the .rst page sphinx-gallery already generates for them).
exclude_patterns = [
    "_build",
    "**.ipynb_checkpoints",
    "auto_examples/**/*.ipynb",
]

numpydoc_show_class_members = False
autodoc_member_order = "bysource"
graphviz_output_format = "svg"
toc_object_entries_show_parents = "hide"

# Autodoc configuration for better handling of Numba classes
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Custom autodoc processing for Numba jitclass
def autodoc_skip_member(app, what, name, obj, skip, options):
    """Skip certain members in autodoc to clean up Numba class documentation."""
    # Skip the class_type attribute that Numba adds
    if name == 'class_type':
        return True
    # Skip internal Numba attributes
    if name.startswith('_numba_'):
        return True
    # Skip other unwanted Numba internal attributes
    if name in ['__dict__', '__weakref__', '_type', '_literal_value']:
        return True
    return skip

def process_docstring(app, what, name, obj, options, lines):
    """Process docstrings to clean up Numba class documentation."""
    if what == "class" and hasattr(obj, 'class_type'):
        # This is a Numba jitclass, clean up the docstring
        if lines and 'jitclass' in str(lines[0]):
            # Replace jitclass type info with cleaner description
            lines[0] = "Numba-compiled parameter class for efficient computation."


def on_missing_reference(app, env, node, contnode):
    if node["reftype"] == "any":
        return contnode
    else:
        return None


def setup(app):
    app.connect("missing-reference", on_missing_reference)
    app.connect("autodoc-skip-member", autodoc_skip_member)
    app.connect("autodoc-process-docstring", process_docstring)

    # sphinx.ext.mathjax only loads its JS on pages with real docutils math
    # nodes (`.. math::`). ModelSpec._repr_html_ embeds LaTeX inside raw HTML
    # (so it also works via Jupyter's rich-display protocol, not just Sphinx),
    # which docutils never sees as "math" - so MathJax would silently not
    # load on those pages without this.
    app.set_html_assets_policy("always")

    # cpp_src = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "vbi", "models", "cpp", "_src"))
    # try:
    #     subprocess.run(["make"], cwd=cpp_src, check=True)
    #     app.info("C++ code compiled successfully.")
    # except subprocess.CalledProcessError as err:
    #     app.warn(f"Failed to compile C++ code in {cpp_src}: {err}")
