name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Runs when you push a version tag like "v1.0.0"
    branches:
      - develop  # Runs when you push to the given branch

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish with manylinux
        uses: pypa/manylinux-action@v1
        with:
          manylinux-version: "2014"  # Use manylinux2014 for broader compatibility
          python-version: "3.10"     # Match your Python version
          command: |
            pip install --upgrade pip
            pip install build twine
            cd vbi/models/cpp/_src
            make
            cd ../../../..  # Navigate back to the root directory
            python -m build
            twine upload --verbose dist/* --repository-url https://upload.pypi.org/legacy/
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}